### ISSUE TITLE
Skills

### ISSUE THREAD

**Issue by mortenm12** [ElectricCoffee/SirenRPG#1]
Right now skills can at the max be 12 with out the prof bonus, and 15 with prof bonus. I think of the possibility to be even better at a skill, than a prof bonus of 3. Can I add two prof bonus' on each other, or could the prof bonus increase.

Another thought, in an older version a character could be untrained, i liked that thought, could an untrained character have a penalty of -3, a trained character a 0 penalty, and a specialist a +3 prof bonus.

**Comment by ElectricCoffee** [comment]
The idea is to have character progression in the game, where the max skill can be raised.

I just wanted to keep the system simple to begin with where the maximum you can get from a random roll is 6.

**Comment by ElectricCoffee** [comment]
This has been resolved in the beta release!
